version: '3.4'

services:
  pluto.netcoretemplate.api:
    image: ${DOCKER_REGISTRY-}blogcoreapiserver
    container_name: blogcoreapiserver
    ports:
      - 8001:5000
    build:
      context: .
      dockerfile: src/Pluto.BlogCore.API/Dockerfile
    environment:
      - CONSUL_TOKEN=''
      - CONSUL_KEY=blogCoreAPI
      - CONSUL_URL=http://www.pluto.icu:8500/